@host = http://localhost:4000/doc

### 
POST {{host}}/my_fold7
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="files"; filename="Mamatlakala.pdf"
Content-Type: application/pdf

< ../doc2/Mamatlakala.pdf
------WebKitFormBoundary--


### 
GET {{host}}
