name: Build, Sign, and Notarize Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-sign-notarize:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Set up signing certificate
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p actions build.keychain
          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain
          security unlock-keychain -p actions ~/Library/Keychains/build.keychain

      - name: Sign the application
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          codesign --deep --force --verbose --sign "Developer ID Application" "dist/RAGDrive-1.0.0-arm64.dmg" --options runtime --timestamp --keychain ~/Library/Keychains/build.keychain

      - name: Notarize the application
        env:
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcrun altool --notarize-app -f "dist/RAGDrive-1.0.0-arm64.dmg" --primary-bundle-id "com.yourcompany.yourapp" --username "your-apple-id@example.com" --password "$APPLE_APP_SPECIFIC_PASSWORD" --team-id "$APPLE_TEAM_ID"
          xcrun altool --notarization-info "$APPLE_APP_SPECIFIC_PASSWORD" -u "your-apple-id@example.com" -p "$APPLE_APP_SPECIFIC_PASSWORD" --output-format xml

      - name: Staple Notarization Ticket
        run: |
          xcrun stapler staple "dist/RAGDrive-1.0.0-arm64.dmg"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/RAGDrive-1.0.0-arm64.dmg
          tag_name: v1.0.0  # Adjust your tag naming as needed
          name: Release v1.0.0
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
