name: Build, Sign, and Notarize Electron App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-sign-notarize:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Find Built DMG Path
        id: find_dmg_path
        run: |
          DMG_PATH=$(find "$PWD/dist" -name "*.dmg" -type f | head -n 1)
          echo "DMG_PATH=$DMG_PATH" >> $GITHUB_ENV
          echo "DMG path found: $DMG_PATH"

      - name: Install Xcode Command Line Tools
        run: sudo xcode-select --install || echo "Command Line Tools already installed"

      - name: Set up keychain and import certificate
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          echo $APPLE_CERTIFICATE | base64 --decode > signing_certificate.p12
          security import signing_certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: "your_keychain_password"

      - name: Code Sign All Components
        run: |
          # Sign all binaries and libraries in the app bundle
          APP_PATH=$(find "$PWD/dist" -name "*.app" -type d | head -n 1)
          find "$APP_PATH" -type f \( -name "*.dylib" -or -name "*.node" -or -name "*.app" -or -name "*.framework" -or -executable \) -exec codesign --deep --force --verify --verbose --options runtime --timestamp --sign "Developer ID Application: Pritam Cristpin (${APPLE_TEAM_ID})" {} \;
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Notarize the DMG
        run: |
          xcrun notarytool submit "$DMG_PATH" --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --wait
        env:
          DMG_PATH: ${{ env.DMG_PATH }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Fetch Notarization Log
        if: always()
        run: |
          SUBMISSION_ID=$(xcrun notarytool history --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --output-format json | jq -r '.notarization-history[0].id')
          xcrun notarytool log --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --output-format json $SUBMISSION_ID > notarization_log.json
          cat notarization_log.json
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Staple Notarization Ticket
        if: success()
        run: |
          xcrun stapler staple "$DMG_PATH"
        env:
          DMG_PATH: ${{ env.DMG_PATH }}