name: "Nidum.ai macOS Build and Release"
on:
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'
      - name: Install dependencies
        run: npm ci
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
      - name: Build and Sign Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          # Decode and import the Apple certificate
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          
          # Build the Electron app with electron-builder
          npm run build
          
          # Find all generated files
          BUILD_FILES=$(find "$PWD/dist" -type f)
          echo "BUILD_FILES<<EOF" >> $GITHUB_ENV
          echo "$BUILD_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Notarize and Staple
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          for file in $BUILD_FILES; do
            if [[ "$file" == *.app ]] || [[ "$file" == *.dmg ]]; then
              echo "Notarizing $file"
              xcrun notarytool submit "$file" --wait --apple-id "$APPLE_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --team-id "$APPLE_TEAM_ID"
              if [ $? -ne 0 ]; then
                echo "Error: Notarization failed for $file"
                exit 1
              fi
              echo "Stapling $file"
              xcrun stapler staple "$file"
              if [ $? -ne 0 ]; then
                echo "Error: Stapling notarization ticket failed for $file"
                exit 1
              fi
            fi
          done
      
      - name: Check if Release Exists
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v${{ env.VERSION }}" > /dev/null 2>&1; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi
      
      - name: Create or Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ env.RELEASE_EXISTS }}" = "true" ]; then
            echo "Updating existing release for version v${{ env.VERSION }}"
            for file in $BUILD_FILES; do
              gh release upload "v${{ env.VERSION }}" "$file" --clobber
            done
          else
            echo "Creating new release for version v${{ env.VERSION }}"
            gh release create "v${{ env.VERSION }}" $BUILD_FILES \
              --title "Release v${{ env.VERSION }}" \
              --generate-notes
          fi
