name: Build, Sign, Notarize, and Release Electron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-sign-notarize-release:
    runs-on: macos-latest
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
      CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      run: |
        npm install
        npm install -g electron-builder@latest

    - name: Setup Python for node-gyp
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Verify custom icon exists
      run: |
        if [ ! -f "path/to/your/icon.icns" ]; then
          echo "Error: Custom icon not found at path/to/your/icon.icns"
          exit 1
        fi

    - name: Create build directory and entitlements file
      run: |
        mkdir -p build
        cat > build/entitlements.mac.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>com.apple.security.cs.allow-jit</key>
            <true/>
            <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
            <true/>
            <key>com.apple.security.cs.allow-dyld-environment-variables</key>
            <true/>
            <key>com.apple.security.network.client</key>
            <true/>
            <key>com.apple.security.network.server</key>
            <true/>
            <key>com.apple.security.files.user-selected.read-write</key>
            <true/>
        </dict>
        </plist>
        EOL

    - name: Update package.json for electron-builder
      run: |
        npm pkg set build.mac.hardenedRuntime=true
        npm pkg set build.mac.gatekeeperAssess=false
        npm pkg set build.mac.entitlements="build/entitlements.mac.plist"
        npm pkg set build.mac.entitlementsInherit="build/entitlements.mac.plist"
        npm pkg set build.mac.icon="path/to/your/icon.icns"  # Ensure the icon path is correct

    - name: Import Apple Developer Certificate
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      run: |
        echo "Importing Apple Developer Certificate..."
        echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        echo "Certificate imported successfully."

    - name: Build Electron App
      run: |
        echo "Building Electron app..."
        electron-builder --config electron-builder.yml  # Explicitly specify the config file if using YAML
        echo "Build completed."

    - name: Get app version
      id: get_version
      run: |
        APP_VERSION=$(node -p "require('./package.json').version")
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "Version: $APP_VERSION"

    - name: Verify built artifacts
      run: |
        echo "Verifying built artifacts..."
        ls -R dist
        if [ ! -f "dist/RAGDrive-${{ env.APP_VERSION }}.dmg" ]; then
          echo "Error: DMG file not found!"
          exit 1
        fi
        echo "DMG_PATH=dist/RAGDrive-${{ env.APP_VERSION }}.dmg" >> $GITHUB_ENV

    - name: Notarize app
      run: |
        echo "Notarizing app..."
        xcrun notarytool submit "${{ env.DMG_PATH }}" \
          --apple-id "$APPLE_ID" \
          --password "$APPLE_APP_SPECIFIC_PASSWORD" \
          --team-id "$APPLE_TEAM_ID" \
          --wait

        if [ $? -ne 0 ]; then
          echo "Error: Notarization failed."
          xcrun notarytool log --apple-id "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID"
          exit 1
        fi
        echo "Notarization completed successfully."

    - name: Staple notarization ticket
      run: |
        echo "Stapling notarization ticket..."
        xcrun stapler staple "${{ env.DMG_PATH }}"
        if [ $? -ne 0 ]; then
          echo "Error: Stapling failed."
          exit 1
        fi
        echo "Stapling completed successfully."

    - name: Verify signing and notarization
      run: |
        echo "Verifying signing and notarization..."
        codesign -dv --verbose=4 "${{ env.DMG_PATH }}"
        spctl -a -vv -t install "${{ env.DMG_PATH }}"
        echo "Verification completed."

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.DMG_PATH }}
        tag_name: v${{ env.APP_VERSION }}
        name: Release v${{ env.APP_VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Clean up
      if: always()
      run: |
        security delete-keychain build.keychain || true
        rm -f certificate.p12 || true