name: Build and Release Electron App

on:
  push:
    branches:
      - main  # Triggers the action on push to main branch
  pull_request:
    branches:
      - main  # Also triggers on pull requests to main branch

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner to build for macOS

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'  # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Upload build artifacts
        if: success()  # Only upload if the build is successful
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: dist/**  # Adjust this path if your output is elsewhere

  release:
    needs: build  # Ensure release job runs only after build job
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        with:
          tag_name: v1.0.0  # Replace with your versioning scheme
          release_name: "Release v1.0.0"  # Replace with your release name
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/RAGDrive-1.0.0-arm64.dmg  # Replace with the actual path to your artifact
          asset_name: RAGDrive-1.0.0-arm64.dmg  # Replace with the actual name of your artifact
          asset_content_type: application/octet-stream
