name: "Nidum.ai Windows Build and Release"

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: Check for package-lock.json
        shell: powershell
        run: |
          if (!(Test-Path "package-lock.json")) {
            Write-Host "package-lock.json not found. Running npm install to generate it."
            npm install
          }

      - name: Install dependencies
        run: npm ci

      - name: Create Self-Signed Certificate
        shell: powershell
        run: |
          openssl req -newkey rsa:2048 -nodes -keyout selfsign.key -x509 -days 365 -out selfsign.crt `
            -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=example.com"
          openssl pkcs12 -export -out selfsign.pfx -inkey selfsign.key -in selfsign.crt -passout pass:1234
          Write-Host "Created self-signed certificate."

      - name: Build Electron App for Windows
        env:
          SIGN_KEY_PATH: selfsign.pfx
          SIGN_KEY_PASSWORD: 1234
        shell: powershell
        run: |
          npm run build-win

          $APP_PATH = Get-ChildItem -Path "./dist" -Filter "*.exe" -Recurse | Select-Object -First 1
          if (-not $APP_PATH) {
            Write-Error "Error: EXE file not found."
            exit 1
          }
          echo "APP_PATH=$($APP_PATH.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

          # Sign the application
          & signtool sign /f $env:SIGN_KEY_PATH /p $env:SIGN_KEY_PASSWORD /tr http://timestamp.digicert.com /td sha256 /fd sha256 $APP_PATH.FullName

      - name: Build NSI Installer
        shell: powershell
        run: |
          $MAKENSIS = (Get-Command makensis -ErrorAction SilentlyContinue)
          if (-not $MAKENSIS) {
            Write-Error "Error: NSIS is not installed."
            exit 1
          }

          $MAKENSIS_SCRIPT = "installer_script.nsi"
          if (!(Test-Path $MAKENSIS_SCRIPT)) {
            Write-Error "Error: NSIS script not found."
            exit 1
          }

          & $MAKENSIS $MAKENSIS_SCRIPT

          $NSI_PATH = Get-ChildItem -Path "./dist" -Filter "*.nsi" -Recurse | Select-Object -First 1
          if (-not $NSI_PATH) {
            Write-Error "Error: NSI installer not found."
            exit 1
          }
          echo "NSI_PATH=$($NSI_PATH.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create or Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
          APP_PATH: ${{ env.APP_PATH }}
          NSI_PATH: ${{ env.NSI_PATH }}
        shell: powershell
        run: |
          if (gh release view "v$($env:VERSION)" 2>$null) {
            Write-Host "Updating existing release for version v$($env:VERSION)"
            gh release upload "v$($env:VERSION)" "$($env:APP_PATH)" "$($env:NSI_PATH)" --clobber
          } else {
            Write-Host "Creating new release for version v$($env:VERSION)"
            gh release create "v$($env:VERSION)" "$($env:APP_PATH)" "$($env:NSI_PATH)" `
              --title "Release v$($env:VERSION)" `
              --generate-notes
